### ISSUE TITLE
Atributos latitude e longitude: documentação conflita com a especificação de precisão

### ISSUE THREAD

**Issue by danielgoncalves** [Abrasel-Nacional/opendelivery#85]
Os atributos `latitude` e `longitude` dos objetos `Service.serviceArea.polygon.geoCoordinates` estão documentados como tipo `number` e `decimal places <= 5`.

Porém, o texto da documentação diz:

"The precision should be at least 5 decimal places"

O que dá a entender que `latitude` e `longitude` devem possuir pelo menos 5 casas decimais, o que é o oposto do que está documentado no tipo do atributo.

## Correção Sugerida 1

O texto da documentação deve ser corrigido para:

"Precision must be up to 5 decimal places"

## Correção Sugerida 2

O tipo dos atributos `latitude` e `longitude` deve ser documentado como:

`number` `decimal places >= 5`

## Referência

* https://abrasel-nacional.github.io/docs/#section/Service

**Comment by gui-camargo** [comment]
Olá @danielgoncalves,

Na verdade essa descrição é gerada automaticamente pelo redoc (que renderiza o yaml do openapi).
Na definição do campo eu declaro dessa maneira:
```
latitude:
                      type: "number"
                      multipleOf: 0.00001
                      description: "Latitude in degrees. Values are restricted to the range [[-90, 90]].\n\n\n\nThe precision should be at least 5 decimal places."
```
O redoc automaticamente converte esse **multipleOf: 0.00001** para a descrição `decimal places <= 5`.
Estava lendo o [comit](https://github.com/Redocly/redoc/pull/1065) do redoc que criou esse convert automático e acredito que é um bug do redoc, porque antes o campo era `decimals <= X`, aí fazia mais sentido.


Vamos levar as suas sugestões para o comite para ver qual o pessoal prefere, mas provavelmente vou ter que tirar esse **multipleOf: 0.00001** porque acredito que não consigo alterar a renderização do HTML.
